/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on May 28, 2011, 9:52:38 PM
 */
package br.pucrs.gui;

import br.pucrs.logic.Associative;
import br.pucrs.logic.Aux2;
import br.pucrs.logic.Direct;
import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mac01-lexsislexsis
 */
public class MainJFrame extends javax.swing.JFrame {
    JFileChooser dialog;
    Direct direct;
    Associative associative;
    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
        pnAssociative.setVisible( false );
        dialog = new JFileChooser();
        dialog.addChoosableFileFilter(new Aux2.TxtFilter());
        direct = new Direct();
        associative = new Associative();
        //para gerar um novo arquivo, descomente abaixo :)
        //Aux2.geraArquivo(100);
        lbAvarage.setVisible(false);lbMiss.setVisible(false);lbHit.setVisible(false);lbTime.setVisible(false);
        lbAvarage1.setVisible(false);lbMiss1.setVisible(false);lbHit1.setVisible(false);lbTime1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMode = new javax.swing.JComboBox();
        pnDirect = new javax.swing.JPanel();
        spnCacheSize = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnWordSize = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spnNumberOfWords = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lbTagAdressSize = new javax.swing.JLabel();
        lbLineAdressSize = new javax.swing.JLabel();
        lbBlockAdressSize = new javax.swing.JLabel();
        lbDataPercentage = new javax.swing.JLabel();
        lbHit = new javax.swing.JLabel();
        lbMiss = new javax.swing.JLabel();
        lbAvarage = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnAssociative = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnCacheSizeAss = new javax.swing.JSpinner();
        spnWordSizeAss = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        butStart = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        spnNumberOfWordsAss = new javax.swing.JSpinner();
        lbTime1 = new javax.swing.JLabel();
        lbHit1 = new javax.swing.JLabel();
        lbMiss1 = new javax.swing.JLabel();
        lbAvarage1 = new javax.swing.JLabel();
        lbBlockAdressSize1 = new javax.swing.JLabel();
        lbTagAdressSize1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cache Mapping");

        cbMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direct", "Associative" }));
        cbMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbModeItemStateChanged(evt);
            }
        });
        cbMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeActionPerformed(evt);
            }
        });

        pnDirect.setBorder(javax.swing.BorderFactory.createTitledBorder("Direct Mapping"));

        spnCacheSize.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnCacheSize.setName("spnCache"); // NOI18N

        jLabel2.setText("Cache size");

        jLabel3.setText("Word size");

        spnWordSize.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnWordSize.setName("spnWordSize"); // NOI18N

        jLabel4.setText("Number of words");

        spnNumberOfWords.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnNumberOfWords.setName("spnNumberOfWords"); // NOI18N

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTagAdressSize.setText("Tag Adress Size: 0");
        lbTagAdressSize.setName("lbTag"); // NOI18N

        lbLineAdressSize.setText("Line Adress Size: 0");
        lbLineAdressSize.setName("lbline"); // NOI18N

        lbBlockAdressSize.setText("Block Adress Size: 0");

        lbDataPercentage.setText("Data Percentage : 0%  ");
        lbDataPercentage.setName("lbTag"); // NOI18N

        lbHit.setForeground(new java.awt.Color(0, 0, 255));
        lbHit.setText("Hit-ratio: 0%");

        lbMiss.setForeground(new java.awt.Color(0, 0, 255));
        lbMiss.setText("Miss-ratio:0%");

        lbAvarage.setForeground(new java.awt.Color(0, 0, 255));
        lbAvarage.setText("Avarage time: 0");

        lbTime.setForeground(new java.awt.Color(0, 0, 255));
        lbTime.setText("Total time: 0");

        jLabel5.setText("Bytes");

        jLabel6.setText("Bits");

        org.jdesktop.layout.GroupLayout pnDirectLayout = new org.jdesktop.layout.GroupLayout(pnDirect);
        pnDirect.setLayout(pnDirectLayout);
        pnDirectLayout.setHorizontalGroup(
            pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDirectLayout.createSequentialGroup()
                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbDataPercentage)
                    .add(pnDirectLayout.createSequentialGroup()
                        .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnDirectLayout.createSequentialGroup()
                                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, spnCacheSize)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(lbTagAdressSize))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lbLineAdressSize)
                                    .add(pnDirectLayout.createSequentialGroup()
                                        .add(spnWordSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel6))
                                    .add(jLabel3)
                                    .add(lbMiss)))
                            .add(jButton1)
                            .add(lbHit))
                        .add(25, 25, 25)
                        .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbAvarage)
                            .add(spnNumberOfWords, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4)
                            .add(lbBlockAdressSize)))
                    .add(lbTime))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnDirectLayout.setVerticalGroup(
            pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDirectLayout.createSequentialGroup()
                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4))
                .add(4, 4, 4)
                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnDirectLayout.createSequentialGroup()
                        .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(spnCacheSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(spnWordSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel5)
                                .add(jLabel6)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(spnNumberOfWords, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbTagAdressSize)
                    .add(lbLineAdressSize)
                    .add(lbBlockAdressSize))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbDataPercentage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnDirectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbHit)
                    .add(lbMiss)
                    .add(lbAvarage))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbTime)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Mapping Mode");

        pnAssociative.setBorder(javax.swing.BorderFactory.createTitledBorder("Associative mapping"));

        jLabel7.setText("Cache size");

        jLabel8.setText("Word size");

        spnCacheSizeAss.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnCacheSizeAss.setName("spnCache"); // NOI18N

        spnWordSizeAss.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnWordSizeAss.setName("spnWordSize"); // NOI18N

        jLabel9.setText("Bytes");

        jLabel10.setText("Bits");

        butStart.setText("Calculate");
        butStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStartActionPerformed(evt);
            }
        });

        jLabel12.setText("Number of words");

        spnNumberOfWordsAss.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(2)));
        spnNumberOfWordsAss.setName("spnNumberOfWords"); // NOI18N

        lbTime1.setForeground(new java.awt.Color(0, 0, 255));
        lbTime1.setText("Total time: 0");

        lbHit1.setForeground(new java.awt.Color(0, 0, 255));
        lbHit1.setText("Hit-ratio: 0%");

        lbMiss1.setForeground(new java.awt.Color(0, 0, 255));
        lbMiss1.setText("Miss-ratio:0%");

        lbAvarage1.setForeground(new java.awt.Color(0, 0, 255));
        lbAvarage1.setText("Avarage time: 0");

        lbBlockAdressSize1.setText("Block Adress Size: 0");

        lbTagAdressSize1.setText("Tag Adress Size: 0");
        lbTagAdressSize1.setName("lbTag"); // NOI18N

        org.jdesktop.layout.GroupLayout pnAssociativeLayout = new org.jdesktop.layout.GroupLayout(pnAssociative);
        pnAssociative.setLayout(pnAssociativeLayout);
        pnAssociativeLayout.setHorizontalGroup(
            pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAssociativeLayout.createSequentialGroup()
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(spnCacheSizeAss, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .add(jLabel7)
                    .add(lbTagAdressSize1))
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnAssociativeLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jLabel9)
                        .add(18, 18, 18)
                        .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnAssociativeLayout.createSequentialGroup()
                                .add(spnWordSizeAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10))
                            .add(jLabel8)))
                    .add(pnAssociativeLayout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbMiss1)
                            .add(lbBlockAdressSize1))))
                .add(18, 18, 18)
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(lbAvarage1)
                        .add(spnNumberOfWordsAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .add(pnAssociativeLayout.createSequentialGroup()
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(butStart)
                    .add(lbHit1)
                    .add(lbTime1))
                .addContainerGap())
        );
        pnAssociativeLayout.setVerticalGroup(
            pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAssociativeLayout.createSequentialGroup()
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel8)
                    .add(jLabel12))
                .add(4, 4, 4)
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(spnCacheSizeAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(spnWordSizeAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(spnNumberOfWordsAss, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(butStart)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbTagAdressSize1)
                    .add(lbBlockAdressSize1))
                .add(11, 11, 11)
                .add(pnAssociativeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbHit1)
                    .add(lbAvarage1)
                    .add(lbMiss1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lbTime1))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pnAssociative, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, cbMode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, pnDirect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbMode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnDirect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnAssociative, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDirect.getAccessibleContext().setAccessibleName("Data");
        pnAssociative.getAccessibleContext().setAccessibleName("Data");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lbAvarage.setVisible(false);lbMiss.setVisible(false);lbHit.setVisible(false);lbTime.setVisible(false);
        direct.setCacheSize( 8 * (Integer) spnCacheSize.getValue() );
        direct.setWordSize(  (Integer) spnWordSize.getValue() );
        direct.setNumberOfWords( (Integer) spnNumberOfWords.getValue() );
        direct.calculate();
        
        lbBlockAdressSize.setText("Block Adress Size: " + direct.getBlockAdressSize() );
        lbTagAdressSize.setText("Tag Adress Size: " + direct.getTagSize() );
        lbLineAdressSize.setText("Line Adress Size: " + direct.getLineAdressSize() );    
        lbDataPercentage.setText(String.format("Data Percentage: %2.2f ", direct.getDataPercentage() ) + "%");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbModeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbModeItemStateChanged
        pnDirect.setVisible( cbMode.getSelectedItem().equals("Direct") );
        pnAssociative.setVisible( cbMode.getSelectedItem().equals("Associative") );
    }//GEN-LAST:event_cbModeItemStateChanged

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Exit?","Confirm",2) == 0 )
            this.dispose();    
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Mapping Simulator Created by Pablo Baldez and Thomas Delgado\nVersion 1.0","About",1);        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int retorno = dialog.showOpenDialog(null);
        if(retorno == JFileChooser.APPROVE_OPTION)
        {
            File arquivo = dialog.getSelectedFile();
            ArrayList<String> adress = Aux2.ReadArchive(arquivo.getAbsolutePath());
            if (cbMode.getSelectedIndex() == 0){
                direct.calculateResults(adress);
                lbAvarage.setVisible(true);lbMiss.setVisible(true);lbHit.setVisible(true);lbTime.setVisible(true);
                lbHit.setText(String.format("Hit-ratio: %2.2f ", direct.getHitRatio()* 100 ) + "%");
                lbMiss.setText(String.format("Miss-ratio: %2.2f ", direct.getMissRatio() * 100) + "%");
                lbAvarage.setText(String.format("Avarage time: %2.2f", + direct.getAvarageTime()) + " us");
                lbTime.setText(String.format("Total time: %2.2f", direct.getTotalTime()) + " us");
            }
            else if(cbMode.getSelectedIndex() == 1){
                associative.LRU(adress);
                
                lbAvarage1.setVisible(true);lbMiss1.setVisible(true);lbHit1.setVisible(true);lbTime1.setVisible(true);
                lbMiss1.setText(String.format("Miss-ratio: %2.2f ", associative.getMissRatio() * 100 ) + "%");
                lbHit1.setText(String.format("Hit-ratio: %2.2f ", associative.getHitRatio() * 100) + "%");              
                lbAvarage1.setText(String.format("Avarage time: %2.2f", + associative.getAvarageTime()) + " us");
                lbTime1.setText(String.format("Total time: %2.2f", associative.getTotalTime()) + " us");
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void butStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStartActionPerformed
        lbAvarage1.setVisible(false);lbMiss1.setVisible(false);lbHit1.setVisible(false);lbTime1.setVisible(false);
        associative.setCacheSize( 8 * (Integer) spnCacheSizeAss.getValue() );
        associative.setWordSize(  (Integer) spnWordSizeAss.getValue() );
        associative.setNumberOfWords( (Integer) spnNumberOfWordsAss.getValue() );
        associative.setNumberOfLines(associative.getCacheSize(), associative.getWordSize());
        associative.createMemory();
        
        lbBlockAdressSize1.setText("Block Adress Size: " + associative.getBlockAdressSize() );
        lbTagAdressSize1.setText("Tag Adress Size: " + associative.getTagSize() );
    }//GEN-LAST:event_butStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butStart;
    private javax.swing.JComboBox cbMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lbAvarage;
    private javax.swing.JLabel lbAvarage1;
    private javax.swing.JLabel lbBlockAdressSize;
    private javax.swing.JLabel lbBlockAdressSize1;
    private javax.swing.JLabel lbDataPercentage;
    private javax.swing.JLabel lbHit;
    private javax.swing.JLabel lbHit1;
    private javax.swing.JLabel lbLineAdressSize;
    private javax.swing.JLabel lbMiss;
    private javax.swing.JLabel lbMiss1;
    private javax.swing.JLabel lbTagAdressSize;
    private javax.swing.JLabel lbTagAdressSize1;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTime1;
    private javax.swing.JPanel pnAssociative;
    private javax.swing.JPanel pnDirect;
    private javax.swing.JSpinner spnCacheSize;
    private javax.swing.JSpinner spnCacheSizeAss;
    private javax.swing.JSpinner spnNumberOfWords;
    private javax.swing.JSpinner spnNumberOfWordsAss;
    private javax.swing.JSpinner spnWordSize;
    private javax.swing.JSpinner spnWordSizeAss;
    // End of variables declaration//GEN-END:variables
}
